Vagrant.configure("2") do |config|
  config.vm.define :server do |srv|
    srv.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
       vb.cpus = 1
       vb.name = "TestServer"
    end
    srv.vm.host_name = "server.training.local"
    srv.vm.network "private_network", ip: "10.0.0.10"
    srv.vm.provision :shell, :path => 'bin/server.sh'
  end

  config.vm.define :client do |clt|
    clt.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "TestMachine"
    end
    clt.vm.hostname = "client.training.local"
    clt.vm.network "private_network", ip: "10.0.0.20"
    clt.vm.provision :shell, :path => 'bin/client.sh'
  end

  config.vm.box_check_update = false
  config.vm.box = 'centos/8'
  config.vm.synced_folder ".", "/vagrant", type: 'virtualbox'

end
